import { type FormEvent, useEffect, useState } from 'react'
import { confirmMFA, createAPIKey, createInvitation, createWebhook, decideApproval, getSecurity, listAPIKeys, listApprovalPolicies, listApprovals, listInvitations, listMembers, listSequences, listWebhooks, revokeAPIKey, saveApprovalPolicy, saveSecurity, saveSequence, setMemberActive, setupMFA } from '../api/operations'
import type { IdentityProfile } from '../api/auth'
import { Badge, Button, EmptyState, PageHeader } from '../components/ui'
import type { APIKey, Approval, ApprovalPolicy, DocumentSequence, Invitation, OrganizationMember, SecuritySettings, Webhook } from '../types/operations'

export function ControlsPage({ profile, onNotice }: { profile: IdentityProfile; onNotice: (value: string) => void }) {
  const [security, setSecurity] = useState<SecuritySettings | null>(null); const [invitations, setInvitations] = useState<Invitation[]>([]); const [members, setMembers] = useState<OrganizationMember[]>([]); const [approvals, setApprovals] = useState<Approval[]>([]); const [sequences, setSequences] = useState<DocumentSequence[]>([]); const [keys, setKeys] = useState<APIKey[]>([]); const [webhooks, setWebhooks] = useState<Webhook[]>([]); const [policies, setPolicies] = useState<ApprovalPolicy[]>([]); const [mfaSecret, setMfaSecret] = useState(''); const [mfaCode, setMfaCode] = useState('')
  async function refresh() { const [s, i, m, a, n, k, w, p] = await Promise.all([getSecurity(), listInvitations(), listMembers(), listApprovals(), listSequences(), listAPIKeys(), listWebhooks(), listApprovalPolicies()]); setSecurity(s); setInvitations(i); setMembers(m); setApprovals(a); setSequences(n); setKeys(k); setWebhooks(w); setPolicies(p) }
  useEffect(() => { void refresh() }, [])
  async function securitySubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await saveSecurity({ require_2fa: f.get('require_2fa') === 'on', approval_threshold: String(f.get('approval_threshold')), session_ttl_minutes: Number(f.get('session_ttl_minutes')) }); await refresh(); onNotice('Kebijakan keamanan diperbarui.') }
  async function invite(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await createInvitation({ email: String(f.get('email')), role_code: String(f.get('role_code')) }); e.currentTarget.reset(); await refresh(); onNotice(`Undangan dibuat. Token sekali tampil: ${result.invitation_token}`) }
  async function sequence(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await saveSequence({ document_type: String(f.get('document_type')), prefix: String(f.get('prefix')), padding: Number(f.get('padding')), reset_policy: String(f.get('reset_policy')) }); await refresh(); onNotice('Format nomor dokumen diperbarui.') }
  async function apiKey(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await createAPIKey({ name: String(f.get('name')), permissions: String(f.get('permissions')).split(',').map((v) => v.trim()).filter(Boolean) }); e.currentTarget.reset(); await refresh(); onNotice(`API key dibuat. Secret sekali tampil: ${result.secret}`) }
  async function webhook(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await createWebhook({ name: String(f.get('name')), endpoint_url: String(f.get('endpoint_url')), subscribed_events: String(f.get('events')).split(',').map((v) => v.trim()).filter(Boolean) }); e.currentTarget.reset(); await refresh(); onNotice(`Webhook dibuat. Signing secret sekali tampil: ${result.signing_secret}`) }
  async function policy(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await saveApprovalPolicy({ document_type: String(f.get('document_type')), minimum_amount: String(f.get('minimum_amount')), minimum_discount_basis_points: Number(f.get('discount_bp')), condition_mode: String(f.get('condition_mode')), approver_role: String(f.get('approver_role')), is_active: true }); await refresh(); onNotice('Kebijakan approval otomatis disimpan.') }
  return <section><PageHeader eyebrow="GOVERNANCE" title="Kontrol organisasi dan integrasi" description="Kelola keamanan, tim, approval, penomoran, serta integrasi mesin-ke-mesin tanpa mengubah aplikasi menjadi portal token." />
    <div className="split-grid"><form className="panel form-panel" onSubmit={(e) => void securitySubmit(e)}><h2>Kebijakan keamanan</h2><label className="check-row"><input type="checkbox" name="require_2fa" defaultChecked={security?.require_2fa} key={String(security?.require_2fa)} />Wajibkan 2FA untuk anggota</label><div className="form-row"><label>Ambang approval<input name="approval_threshold" defaultValue={security?.approval_threshold_minor ?? 0} required /></label><label>Durasi sesi (menit)<input type="number" min="15" max="43200" name="session_ttl_minutes" defaultValue={security?.session_ttl_minutes ?? 480} required /></label></div><Button>Simpan kebijakan</Button><div className="callout"><strong>Authenticator pribadi</strong><span>{mfaSecret ? `Secret: ${mfaSecret}` : 'Aktifkan MFA Anda sebelum mewajibkannya untuk organisasi.'}</span></div><div className="form-row"><Button type="button" variant="secondary" onClick={() => void setupMFA(profile.email).then(v => setMfaSecret(v.secret))}>Siapkan MFA</Button><label>Kode 6 digit<input value={mfaCode} onChange={e => setMfaCode(e.target.value)} maxLength={6} /></label><Button type="button" onClick={() => void confirmMFA(mfaCode).then(v => { setMfaSecret(''); onNotice(`MFA aktif. Recovery code: ${v.recovery_codes.join(', ')}`) })}>Konfirmasi</Button></div></form>
      <form className="panel form-panel" onSubmit={(e) => void invite(e)}><h2>Undang anggota</h2><label>Email<input type="email" name="email" required /></label><label>Peran<select name="role_code"><option>ACCOUNTANT</option><option>FINANCE</option><option>AUDITOR</option><option>READ_ONLY</option><option>OWNER</option></select></label><Button>Kirim undangan</Button><div className="record-list">{members.map(m => <div className="record-row" key={m.user_id}><div><strong>{m.full_name}</strong><small>{m.email} · {m.role_code}</small></div>{m.user_id !== profile.user_id && <Button type="button" variant="ghost" onClick={() => void setMemberActive(m.user_id, !m.is_active).then(refresh)}>{m.is_active ? 'Nonaktifkan' : 'Aktifkan'}</Button>}</div>)}</div></form></div>
    <div className="split-grid"><form className="panel form-panel" onSubmit={(e) => void sequence(e)}><h2>Penomoran dokumen</h2><div className="form-row"><label>Jenis dokumen<select name="document_type">{['SALES_QUOTE','SALES_ORDER','DELIVERY','SALES_INVOICE','PURCHASE_ORDER','GOODS_RECEIPT','PURCHASE_INVOICE'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Prefix<input name="prefix" placeholder="INV" required /></label></div><div className="form-row"><label>Digit nomor<input type="number" name="padding" min="1" max="12" defaultValue="5" /></label><label>Reset<select name="reset_policy"><option>YEARLY</option><option>MONTHLY</option><option>NEVER</option></select></label></div><Button>Simpan format</Button></form>
      <div className="panel"><div className="panel-heading"><div><h2>Antrean persetujuan</h2><p>Keputusan sensitif tercatat bersama aktor.</p></div><Badge tone="warning">{approvals.filter((a) => a.status === 'PENDING').length} pending</Badge></div>{approvals.length === 0 ? <EmptyState>Belum ada permintaan approval.</EmptyState> : <div className="table-wrap"><table><thead><tr><th>Entitas</th><th>Nilai</th><th>Status</th><th /></tr></thead><tbody>{approvals.map((a) => <tr key={a.id}><td>{a.entity_type}<small className="block mono">{a.entity_id.slice(0, 8)}</small></td><td className="mono">{a.amount_minor.toLocaleString('id-ID')}</td><td><Badge tone={a.status === 'APPROVED' ? 'success' : 'warning'}>{a.status}</Badge></td><td>{a.status === 'PENDING' && <div className="flex gap-1"><Button variant="secondary" onClick={() => void decideApproval(a.id, 'APPROVED').then(refresh)}>Setujui</Button><Button variant="ghost" onClick={() => void decideApproval(a.id, 'REJECTED').then(refresh)}>Tolak</Button></div>}</td></tr>)}</tbody></table></div>}</div></div>
    <form className="panel form-panel wide-form" onSubmit={(e) => void policy(e)}><div className="section-title"><div><span className="section-icon">AP</span><h2>Approval otomatis per dokumen</h2></div><Badge tone="info">{policies.length} kebijakan</Badge></div><div className="form-row"><label>Jenis dokumen<select name="document_type">{['SALES_QUOTE','SALES_ORDER','DELIVERY','SALES_INVOICE','PURCHASE_ORDER','GOODS_RECEIPT','PURCHASE_INVOICE','PURCHASE_RETURN','SALES_RETURN'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Nilai minimum<input name="minimum_amount" defaultValue="0" required /></label><label>Diskon minimum (basis point)<input type="number" min="0" max="10000" name="discount_bp" defaultValue="0" /></label><label>Logika<select name="condition_mode"><option>OR</option><option>AND</option></select></label><label>Penyetuju<select name="approver_role"><option>OWNER</option><option>FINANCE</option><option>ACCOUNTANT</option></select></label></div><Button>Simpan kebijakan</Button></form>
    <div className="split-grid"><form className="panel form-panel" onSubmit={(e) => void apiKey(e)}><h2>API key</h2><label>Nama<input name="name" placeholder="Integrasi ERP" required /></label><label>Permissions<input name="permissions" defaultValue="documents:read,reports:read" required /></label><div className="callout"><strong>Bukan login pengguna</strong><span>Key hanya untuk integrasi server dan nilai asli ditampilkan satu kali.</span></div><Button>Buat API key</Button></form>
      <form className="panel form-panel" onSubmit={(e) => void webhook(e)}><h2>Webhook</h2><label>Nama<input name="name" required /></label><label>HTTPS endpoint<input type="url" name="endpoint_url" placeholder="https://erp.example.com/hooks/loka" required /></label><label>Event<input name="events" defaultValue="document.created,journal.posted" required /></label><Button>Buat webhook</Button></form></div>
    <div className="three-grid"><Record title="Undangan" badge={`${invitations.length} anggota`} empty="Belum ada undangan.">{invitations.map((i) => <div className="record-row" key={i.id}><div><strong>{i.email}</strong><small>{i.role_code}</small></div><Badge tone={i.status === 'PENDING' ? 'warning' : 'success'}>{i.status}</Badge></div>)}</Record><Record title="Nomor dokumen" badge={`${sequences.length} format`} empty="Belum ada format.">{sequences.map((s) => <div className="record-row" key={s.id}><div><strong>{s.document_type}</strong><small>{s.prefix} · {s.reset_policy}</small></div><Badge>{s.next_number}</Badge></div>)}</Record><Record title="Integrasi aktif" badge={`${keys.length + webhooks.length} koneksi`} empty="Belum ada integrasi.">{keys.map((k) => <div className="record-row" key={k.id}><div><strong>{k.name}</strong><small className="mono">{k.key_prefix}…</small></div>{k.is_active && <Button variant="ghost" onClick={() => void revokeAPIKey(k.id).then(refresh)}>Cabut</Button>}</div>)}{webhooks.map((w) => <div className="record-row" key={w.id}><div><strong>{w.name}</strong><small>{w.endpoint_url}</small></div><Badge tone="success">Webhook</Badge></div>)}</Record></div>
  </section>
}

function Record({ title, badge, empty, children }: { title: string; badge: string; empty: string; children: React.ReactNode }) { return <div className="panel"><div className="panel-heading"><div><h2>{title}</h2></div><Badge>{badge}</Badge></div><div className="record-list">{children || <EmptyState>{empty}</EmptyState>}</div></div> }
