import { type FormEvent, useEffect, useState } from 'react'
import { adjustInventory, createDocument, listDocuments, listInventoryBalances, listItems, listReservations, listWarehouses, releaseReservation, reserveInventory, stockOpname, transferInventory, transitionDocument } from '../api/operations'
import { listContacts } from '../api/accounting'
import { listProjects } from '../api/projects'
import { openDocumentPrint } from '../api/print'
import type { Project } from '../types/reports'
import { Badge, Button, DataEntryGuide, EmptyState, PageHeader } from '../components/ui'
import type { Contact } from '../types/accounting'
import type { BusinessDocument, InventoryBalance, InventoryReservation, Item, Warehouse } from '../types/operations'

const types = ['SALES_QUOTE','SALES_ORDER','DELIVERY','SALES_INVOICE','SALES_RETURN','PURCHASE_REQUISITION','PURCHASE_ORDER','GOODS_RECEIPT','PURCHASE_INVOICE','PURCHASE_RETURN']
export function DocumentsPage({ onNotice }: { onNotice: (value: string) => void }) {
  const [documents, setDocuments] = useState<BusinessDocument[]>([]); const [items, setItems] = useState<Item[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [balances, setBalances] = useState<InventoryBalance[]>([]); const [contacts, setContacts] = useState<Contact[]>([]); const [reservations, setReservations] = useState<InventoryReservation[]>([]); const [projects, setProjects] = useState<Project[]>([])
  const [currency, setCurrency] = useState('IDR')
  const [loading, setLoading] = useState(true)
  async function refresh() {
    setLoading(true)
    const results = await Promise.allSettled([listDocuments(), listItems(), listWarehouses(), listInventoryBalances(), listContacts(), listReservations(), listProjects('')])
    const [d, i, w, b, c, r, p] = results
    if (d.status === 'fulfilled') setDocuments(d.value ?? [])
    if (i.status === 'fulfilled') setItems(i.value ?? [])
    if (w.status === 'fulfilled') setWarehouses(w.value ?? [])
    if (b.status === 'fulfilled') setBalances(b.value ?? [])
    if (c.status === 'fulfilled') setContacts(c.value ?? [])
    if (r.status === 'fulfilled') setReservations(r.value ?? [])
    if (p.status === 'fulfilled') setProjects(p.value ?? [])
    const failed = results.filter((result) => result.status === 'rejected').length
    if (failed > 0) onNotice(`${failed} data Jual Beli belum berhasil dimuat. Halaman tetap dapat digunakan.`)
    setLoading(false)
  }
  useEffect(() => { void refresh() }, [])
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const item = items.find((x) => x.id === f.get('item_id')); const due = String(f.get('due_date')); await createDocument({ document_type: String(f.get('document_type')), contact_id: f.get('contact_id') || null, project_id: f.get('project_id') || null, currency_code: String(f.get('currency_code') || 'IDR'), exchange_rate_numerator: Number(f.get('exchange_rate_numerator') || 0), exchange_rate_denominator: Number(f.get('exchange_rate_denominator') || 0), warehouse_id: f.get('warehouse_id') || null, document_date: String(f.get('document_date')), due_date: due || null, notes: String(f.get('notes')), lines: [{ item_id: item?.id ?? null, unit_id: item?.base_unit_id ?? null, description: String(f.get('description')), quantity: String(f.get('quantity')), unit_price: String(f.get('unit_price')), discount: String(f.get('discount') || '0'), tax: String(f.get('tax') || '0') }] }); e.currentTarget.reset(); await refresh(); onNotice('Dokumen bisnis berhasil dibuat sebagai draft.') }
  async function adjust(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await adjustInventory({ item_id: String(f.get('item_id')), warehouse_id: String(f.get('warehouse_id')), quantity_delta: String(f.get('quantity_delta')), value_delta: String(f.get('value_delta')) }); e.currentTarget.reset(); await refresh(); onNotice('Penyesuaian stok berhasil dicatat.') }
  async function advance(document: BusinessDocument) { const next = document.status === 'DRAFT' ? 'OPEN' : document.status === 'PENDING_APPROVAL' ? 'APPROVED' : document.status === 'APPROVED' ? 'OPEN' : document.status === 'OPEN' || document.status === 'PARTIAL' ? 'COMPLETED' : ''; if (!next) return; const result = await transitionDocument(document.id, next); await refresh(); onNotice(result.status === 'PENDING_APPROVAL' ? 'Dokumen masuk antrean approval.' : result.status === 'COMPLETED' ? 'Dokumen selesai; jurnal dan subledger sudah diposting.' : `Status dokumen menjadi ${result.status}.`) }
  async function transfer(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await transferInventory({ item_id: String(f.get('item_id')), from_warehouse_id: String(f.get('from')), to_warehouse_id: String(f.get('to')), quantity: String(f.get('quantity')) }); e.currentTarget.reset(); await refresh(); onNotice('Transfer antar gudang berhasil dicatat.') }
  async function opname(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await stockOpname({ item_id: String(f.get('item_id')), warehouse_id: String(f.get('warehouse_id')), counted_quantity: String(f.get('counted')), surplus_unit_cost: String(f.get('unit_cost') || '0') }); e.currentTarget.reset(); await refresh(); onNotice('Hasil stock opname dicatat sebagai movement append-only.') }
  async function reserve(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await reserveInventory({ document_id: String(f.get('document_id')), item_id: String(f.get('item_id')), warehouse_id: String(f.get('warehouse_id')), quantity: String(f.get('quantity')) }); e.currentTarget.reset(); await refresh(); onNotice('Stok berhasil direservasi.') }
  const inventoryItems = items.filter((i) => i.item_type === 'INVENTORY')
  return <section><PageHeader eyebrow="COMMERCE" title="Penjualan, pembelian, dan persediaan" description="Siklus dokumen terpadu dari penawaran dan pesanan sampai pengiriman, penerimaan, invoice, serta retur." />
    <DataEntryGuide steps={['Pilih jenis dokumen, tanggal, kontak, produk, dan gudang yang sesuai.', 'Isi kuantitas, harga, diskon atau pajak; gunakan kurs hanya untuk transaksi valuta asing.', 'Klik “Buat draft”, periksa dokumen di daftar, lalu gunakan tombol status untuk mengajukan dan menyelesaikannya.', 'Gunakan form persediaan hanya untuk adjustment, transfer, opname, atau reservasi stok.']} note="Master kontak, produk, dan gudang sebaiknya dibuat terlebih dahulu. Penyelesaian dokumen dapat membentuk jurnal dan pergerakan stok." />
    {loading && <div className="loading" role="status">Memuat data penjualan dan pembelian…</div>}
    <div className="split-grid"><form className="panel form-panel" onSubmit={(e) => void create(e)}><h2>Dokumen baru</h2><div className="form-row"><label>Jenis<select name="document_type">{types.map((t) => <option key={t}>{t}</option>)}</select></label><label>Tanggal<input type="date" name="document_date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Jatuh tempo<input type="date" name="due_date" /></label></div><div className="form-row"><label>Kontak<select name="contact_id"><option value="">Tanpa kontak</option>{contacts.map((c) => <option key={c.id} value={c.id}>{c.name} · {c.type}</option>)}</select></label><label>Produk<select name="item_id"><option value="">Tanpa master produk</option>{items.map((i) => <option key={i.id} value={i.id}>{i.sku} · {i.name}</option>)}</select></label><label>Gudang<select name="warehouse_id"><option value="">Tanpa gudang</option>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label><label>Proyek<select name="project_id"><option value="">Tanpa proyek</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label></div><label>Deskripsi<input name="description" required /></label><div className="form-row"><label>Kuantitas<input name="quantity" defaultValue="1" inputMode="decimal" required /></label><label>Harga satuan<input name="unit_price" defaultValue="0" inputMode="numeric" required /></label><label>Diskon<input name="discount" defaultValue="0" inputMode="numeric" /></label><label>Pajak<input name="tax" defaultValue="0" inputMode="numeric" /></label></div><div className="form-row"><label>Mata uang<input name="currency_code" value={currency} onChange={(e) => setCurrency(e.target.value.toUpperCase())} maxLength={3} /></label>{currency !== 'IDR' && <><label>Kurs (Rp per 1 {currency})<input name="exchange_rate_numerator" type="number" min={1} defaultValue={16000} /></label><label>Per<input name="exchange_rate_denominator" type="number" min={1} defaultValue={1} /></label></>}</div>{currency !== 'IDR' && <div className="callout"><strong>Valas</strong><span>Nilai dokumen tetap dalam {currency}; jurnal diposting dalam rupiah memakai kurs ini. Surat jalan dan penerimaan barang harus tetap rupiah karena langsung menilai persediaan.</span></div>}<label>Catatan<input name="notes" /></label><Button>Buat draft</Button></form>
      <form className="panel form-panel" onSubmit={(e) => void adjust(e)}><h2>Penyesuaian persediaan</h2><label>Produk persediaan<select name="item_id" required><option value="">Pilih produk</option>{inventoryItems.map((i) => <option key={i.id} value={i.id}>{i.sku} · {i.name}</option>)}</select></label><label>Gudang<select name="warehouse_id" required><option value="">Pilih gudang</option>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label><div className="form-row"><label>Perubahan kuantitas<input name="quantity_delta" placeholder="10 atau -2" required /></label><label>Perubahan nilai<input name="value_delta" defaultValue="0" required /></label></div><div className="callout"><strong>Audit stok</strong><span>Setiap perubahan menjadi movement append-only dan stok negatif ditolak.</span></div><Button disabled={inventoryItems.length === 0 || warehouses.length === 0}>Catat adjustment</Button></form></div>
    <div className="three-grid"><form className="panel form-panel" onSubmit={(e) => void transfer(e)}><h2>Transfer gudang</h2><label>Produk<select name="item_id" required>{inventoryItems.map((i) => <option key={i.id} value={i.id}>{i.sku} · {i.name}</option>)}</select></label><div className="form-row"><label>Dari<select name="from" required>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></label><label>Ke<select name="to" required>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></label></div><label>Kuantitas<input name="quantity" required /></label><Button>Transfer stok</Button></form><form className="panel form-panel" onSubmit={(e) => void opname(e)}><h2>Stock opname</h2><label>Produk<select name="item_id" required>{inventoryItems.map((i) => <option key={i.id} value={i.id}>{i.sku} · {i.name}</option>)}</select></label><label>Gudang<select name="warehouse_id" required>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></label><div className="form-row"><label>Hasil hitung<input name="counted" required /></label><label>Biaya surplus/unit<input name="unit_cost" defaultValue="0" /></label></div><Button>Catat opname</Button></form><form className="panel form-panel" onSubmit={(e) => void reserve(e)}><h2>Reservasi stok</h2><label>Sales order<select name="document_id" required>{documents.filter((d) => d.document_type === 'SALES_ORDER' && !['COMPLETED','CANCELLED'].includes(d.status)).map((d) => <option key={d.id} value={d.id}>{d.number}</option>)}</select></label><label>Produk<select name="item_id" required>{inventoryItems.map((i) => <option key={i.id} value={i.id}>{i.sku} · {i.name}</option>)}</select></label><div className="form-row"><label>Gudang<select name="warehouse_id" required>{warehouses.map((w) => <option key={w.id} value={w.id}>{w.code}</option>)}</select></label><label>Kuantitas<input name="quantity" required /></label></div><Button>Reservasi</Button></form></div>
    <div className="panel data-panel"><div className="panel-heading"><div><h2>Dokumen terbaru</h2><p>Completion mem-post journal, open item, dan stok secara atomik.</p></div><Badge tone="info">{documents.length} dokumen</Badge></div>{documents.length === 0 ? <EmptyState>Belum ada dokumen bisnis.</EmptyState> : <div className="table-wrap"><table><thead><tr><th>Nomor</th><th>Jenis</th><th>Tanggal</th><th>Status</th><th className="number">Nilai</th><th /></tr></thead><tbody>{documents.map((d) => <tr key={d.id}><td className="mono">{d.number}</td><td><span className="type-tag">{d.document_type}</span></td><td>{d.document_date.slice(0, 10)}</td><td><Badge tone={d.status === 'COMPLETED' ? 'success' : d.status === 'PENDING_APPROVAL' ? 'warning' : 'neutral'}>{d.status}</Badge></td><td className="number mono">{d.total_minor.toLocaleString('id-ID')}</td><td><div className="flex justify-end gap-1">{['DRAFT','PENDING_APPROVAL','APPROVED','OPEN','PARTIAL'].includes(d.status) && <Button variant="secondary" onClick={() => void advance(d)}>{d.status === 'DRAFT' ? 'Ajukan' : d.status === 'PENDING_APPROVAL' ? 'Cek approval' : d.status === 'APPROVED' ? 'Buka' : 'Selesaikan'}</Button>}<Button variant="ghost" icon="printer" title="Cetak PDF" onClick={() => void openDocumentPrint(d.id, 'pdf')}>PDF</Button><Button variant="ghost" onClick={() => void openDocumentPrint(d.id, 'html')}>Pratinjau</Button></div></td></tr>)}</tbody></table></div>}</div>
    <div className="panel data-panel"><div className="panel-heading"><div><h2>Saldo per gudang</h2><p>Kuantitas dan valuasi stok saat ini.</p></div><Badge>{balances.length} posisi</Badge></div>{balances.length === 0 ? <EmptyState>Belum ada saldo persediaan.</EmptyState> : <div className="table-wrap"><table><thead><tr><th>Produk</th><th>Gudang</th><th className="number">Kuantitas</th><th className="number">Nilai</th></tr></thead><tbody>{balances.map((b) => <tr key={`${b.item_id}-${b.warehouse_id}`}><td><strong>{b.item_name}</strong><small className="block mono">{b.sku}</small></td><td>{b.warehouse_name}<small className="block mono">{b.warehouse_code}</small></td><td className="number mono">{b.quantity}</td><td className="number mono">{b.value_minor.toLocaleString('id-ID')}</td></tr>)}</tbody></table></div>}</div>
    {reservations.length > 0 && <div className="panel data-panel"><div className="panel-heading"><div><h2>Reservasi aktif</h2><p>Stok yang ditahan untuk sales order.</p></div><Badge tone="warning">{reservations.filter((r) => r.status === 'ACTIVE').length} aktif</Badge></div><div className="table-wrap"><table><thead><tr><th>Dokumen</th><th>Produk</th><th>Kuantitas</th><th>Status</th><th /></tr></thead><tbody>{reservations.map((r) => <tr key={r.id}><td className="mono">{r.document_id.slice(0, 8)}</td><td className="mono">{r.item_id.slice(0, 8)}</td><td className="mono">{r.quantity}</td><td><Badge>{r.status}</Badge></td><td>{r.status === 'ACTIVE' && <Button variant="ghost" onClick={() => void releaseReservation(r.id).then(refresh)}>Lepas</Button>}</td></tr>)}</tbody></table></div></div>}
  </section>
}
