import { Badge, Button, PageHeader } from '../components/ui'
import type { PageKey } from '../components/Layout'

export type FeatureDomain = 'general-ledger' | 'cash-bank' | 'sales' | 'purchases' | 'inventory' | 'assets'
type Feature = { name: string; description: string; target?: PageKey; state?: 'ready' | 'connector' }
type Domain = { eyebrow: string; title: string; description: string; features: Feature[] }

const domains: Record<FeatureDomain, Domain> = {
  'general-ledger': { eyebrow: 'BUKU BESAR', title: 'Pusat pencatatan dan anggaran', description: 'Akun, jurnal, histori akun, recurring entry, anggaran, serta proses tutup buku dalam satu domain.', features: [
    { name: 'Akun perkiraan', description: 'Chart of accounts, akun induk, impor dan ekspor.', target: 'accounts' }, { name: 'Pencatatan beban', description: 'Beban langsung dengan posting jurnal.', target: 'advanced' }, { name: 'Pencatatan gaji', description: 'Payroll run dan jurnal gaji atomik.', target: 'payroll' }, { name: 'Jurnal umum', description: 'Draft, posting, reversal, dan saldo awal.', target: 'journal' }, { name: 'Monitor anggaran', description: 'Budget variance terhadap realisasi.', target: 'advanced' }, { name: 'Transfer anggaran', description: 'Kelola alokasi lewat dimensi dan jurnal.', target: 'advanced' }, { name: 'Anggaran', description: 'Budget per akun dan periode.', target: 'advanced' }, { name: 'Histori akun', description: 'Ledger yang dapat difilter dan diekspor.', target: 'ledger' }, { name: 'Log aktivitas jurnal', description: 'Audit log append-only.', target: 'advanced' },
  ]},
  'cash-bank': { eyebrow: 'KAS & BANK', title: 'Kas, bank, dan rekonsiliasi', description: 'Catat uang masuk/keluar, impor rekening koran, pencocokan transaksi, dan rekonsiliasi.', features: [
    { name: 'Pembayaran', description: 'Pembayaran utang dan alokasi open item.', target: 'operations' }, { name: 'Penerimaan', description: 'Penerimaan piutang dan alokasi pembayaran.', target: 'operations' }, { name: 'Transfer bank', description: 'Pemindahan dana melalui jurnal berimbang.', target: 'journal' }, { name: 'Rekening koran', description: 'Impor transaksi bank dengan external ID.', target: 'advanced' }, { name: 'Histori bank', description: 'Transaksi per rekening dan status matching.', target: 'advanced' }, { name: 'Rekonsiliasi bank', description: 'Bandingkan statement dengan saldo ledger.', target: 'advanced' }, { name: 'SmartLink e-Banking', description: 'Memerlukan kontrak dan kredensial bank.', state: 'connector' }, { name: 'Virtual Account', description: 'Memerlukan provider VA dan webhook pembayaran.', state: 'connector' }, { name: 'e-Payment', description: 'Memerlukan payment gateway yang dipilih.', state: 'connector' },
  ]},
  sales: { eyebrow: 'PENJUALAN', title: 'Siklus penjualan lengkap', description: 'Dari penawaran sampai retur, invoice, penerimaan, harga, dan analitik pelanggan.', features: [
    { name: 'Penawaran penjualan', description: 'Sales quote dengan workflow approval.', target: 'documents' }, { name: 'Pesanan penjualan', description: 'Sales order dan reservasi stok.', target: 'documents' }, { name: 'Pengiriman pesanan', description: 'Delivery berbasis gudang.', target: 'documents' }, { name: 'Uang muka penjualan', description: 'Dicatat sebagai penerimaan/liabilitas pelanggan.', target: 'operations' }, { name: 'Faktur penjualan', description: 'Invoice, piutang, pajak, dan jurnal.', target: 'documents' }, { name: 'Penerimaan penjualan', description: 'Pelunasan penuh atau parsial.', target: 'operations' }, { name: 'Retur penjualan', description: 'Sales return dan pembalikan stok/jurnal.', target: 'documents' }, { name: 'Kategori pelanggan', description: 'Segmentasi melalui kontak dan dimensi.', target: 'operations' }, { name: 'Pelanggan', description: 'Master kontak pelanggan.', target: 'operations' }, { name: 'Harga & diskon', description: 'Diskon baris dan kontrol approval.', target: 'documents' }, { name: 'Komisi & target', description: 'Dikelola melalui dimensi, budget, dan laporan.', target: 'advanced' }, { name: 'e-Commerce', description: 'Memerlukan konektor marketplace.', state: 'connector' }, { name: 'Check in sales', description: 'Memerlukan aplikasi lapangan/lokasi.', state: 'connector' },
  ]},
  purchases: { eyebrow: 'PEMBELIAN', title: 'Siklus pembelian dan pemasok', description: 'Permintaan, pesanan, penerimaan, invoice, pembayaran, retur, dan kontrol pemasok.', features: [
    { name: 'Permintaan pembelian', description: 'Purchase requisition sebelum order.', target: 'documents' }, { name: 'Pesanan pembelian', description: 'Purchase order dengan approval.', target: 'documents' }, { name: 'Penerimaan barang', description: 'Goods receipt dan mutasi persediaan.', target: 'documents' }, { name: 'Uang muka pembelian', description: 'Pembayaran sebelum invoice.', target: 'operations' }, { name: 'Faktur pembelian', description: 'Purchase invoice dan utang usaha.', target: 'documents' }, { name: 'Pembayaran pembelian', description: 'Pelunasan utang pemasok.', target: 'operations' }, { name: 'Retur pembelian', description: 'Purchase return dan koreksi stok.', target: 'documents' }, { name: 'Harga pemasok', description: 'Harga pada histori dokumen pembelian.', target: 'documents' }, { name: 'Kategori pemasok', description: 'Segmentasi kontak pemasok.', target: 'operations' }, { name: 'Pemasok', description: 'Master supplier dan saldo utang.', target: 'operations' }, { name: 'Perintah pembayaran', description: 'Approval sebelum pembayaran.', target: 'controls' }, { name: 'Transfer pemasok', description: 'Pembayaran lintas dokumen pemasok.', target: 'operations' },
  ]},
  inventory: { eyebrow: 'PERSEDIAAN', title: 'Persediaan, gudang, dan pemenuhan', description: 'Master barang, mutasi append-only, reservasi, stock opname, dan pekerjaan produksi.', features: [
    { name: 'Permintaan barang', description: 'Reservasi dan permintaan melalui dokumen.', target: 'documents' }, { name: 'Pemindahan barang', description: 'Transfer antar gudang.', target: 'documents' }, { name: 'Penyesuaian persediaan', description: 'Adjustment kuantitas dan nilai.', target: 'documents' }, { name: 'Pekerjaan pesanan', description: 'Manufacturing order.', target: 'manufacturing' }, { name: 'Penambahan bahan baku', description: 'Pemakaian raw material pada order produksi.', target: 'manufacturing' }, { name: 'Penyelesaian pesanan', description: 'Kapitalisasi barang jadi.', target: 'manufacturing' }, { name: 'Perintah & hasil stock opname', description: 'Perhitungan dan movement koreksi.', target: 'documents' }, { name: 'Barang & jasa', description: 'Inventory, non-inventory, dan service item.', target: 'products' }, { name: 'Gudang', description: 'Master gudang dan alamat.', target: 'products' }, { name: 'Satuan barang', description: 'Unit of measure dan presisi.', target: 'products' }, { name: 'Kategori & merek', description: 'Klasifikasi melalui dimensi item.', target: 'advanced' }, { name: 'Pemenuhan pesanan', description: 'Reservasi, delivery, dan completion.', target: 'documents' }, { name: 'Barang per gudang', description: 'Saldo kuantitas dan valuasi.', target: 'documents' }, { name: 'Stok minimum', description: 'Pantau posisi stok untuk reorder.', target: 'products' },
  ]},
  assets: { eyebrow: 'ASET TETAP', title: 'Siklus hidup aset tetap', description: 'Akuisisi, depresiasi, perubahan, lokasi, pemindahan, dan disposisi dengan jejak jurnal.', features: [
    { name: 'Aset tetap', description: 'Register aset dan akun terkait.', target: 'advanced' }, { name: 'Kategori aset', description: 'Kelompok aset melalui dimensi.', target: 'advanced' }, { name: 'Kategori pajak aset', description: 'Kelompok fiskal dan masa manfaat.', target: 'compliance' }, { name: 'Perubahan aset tetap', description: 'Perubahan nilai melalui jurnal terkontrol.', target: 'advanced' }, { name: 'Disposisi aset tetap', description: 'Pelepasan aset dan gain/loss.', target: 'advanced' }, { name: 'Pindah aset', description: 'Perubahan lokasi memakai dimensi.', target: 'advanced' }, { name: 'Aset per lokasi', description: 'Pelaporan aset berdasarkan dimensi lokasi.', target: 'reports' },
  ]},
}

export function FeatureDirectoryPage({ domain, onNavigate }: { domain: FeatureDomain; onNavigate: (page: PageKey) => void }) {
  const value = domains[domain]; const live = value.features.filter((feature) => feature.state !== 'connector').length
  return <section><PageHeader eyebrow={value.eyebrow} title={value.title} description={value.description} action={<Badge tone="success">{live} kapabilitas siap</Badge>} />
    <div className="capability-summary"><div><strong>{value.features.length}</strong><span>fitur terpetakan</span></div><div><strong>{live}</strong><span>siap digunakan</span></div><div><strong>{value.features.length - live}</strong><span>perlu konektor</span></div></div>
    <div className="capability-grid">{value.features.map((feature) => <article className="panel capability-card" key={feature.name}><div><span className="capability-mark">{feature.name.slice(0, 2).toUpperCase()}</span><Badge tone={feature.state === 'connector' ? 'warning' : 'success'}>{feature.state === 'connector' ? 'Perlu konektor' : 'Tersedia'}</Badge></div><h2>{feature.name}</h2><p>{feature.description}</p>{feature.target ? <Button variant="secondary" onClick={() => onNavigate(feature.target!)}>Buka fitur</Button> : <Button variant="ghost" onClick={() => onNavigate('controls')}>Konfigurasi integrasi</Button>}</article>)}</div>
  </section>
}
