import { type FormEvent, useEffect, useMemo, useState } from 'react'
import { AxiosError } from 'axios'
import { createContact, postOpeningBalance, saveLocalization, updateSettings } from '../api/accounting'
import { createInvitation, saveOnboarding } from '../api/operations'
import { Badge, Button, Card, PageHeader, cx } from '../components/ui'
import type { PageKey } from '../lib/menu'
import type { Account, AccountingSettings, ApiEnvelope } from '../types/accounting'
import type { Onboarding } from '../types/operations'

const steps = [
  ['company', 'Profil perusahaan', 'Legalitas dan identitas pajak'], ['books', 'Pengaturan buku', 'Periode fiskal dan zona waktu'],
  ['business', 'Jenis usaha', 'Sesuaikan workflow yang dipakai'], ['coa', 'Daftar akun', 'Review struktur chart of accounts'],
  ['opening', 'Saldo awal', 'Mulai dari posisi keuangan yang benar'], ['contacts', 'Kontak', 'Pelanggan atau supplier pertama'],
  ['catalog', 'Produk dan gudang', 'Opsional untuk usaha berbasis barang'], ['controls', 'Kontrol dokumen', 'Penomoran, bank, dan pajak'],
  ['team', 'Undang tim', 'Akses accountant dan finance'], ['review', 'Siap digunakan', 'Review kesiapan workspace'],
] as const
const workflowOptions = [['SALES','Penjualan'],['PURCHASING','Pembelian'],['INVENTORY','Persediaan'],['PAYROLL','Payroll'],['MANUFACTURING','Manufaktur'],['MULTI_CURRENCY','Multi-currency'],['TAX','Pajak Indonesia']] as const

export function GetStartedPage({ onboarding, settings, accounts, onChanged, onNavigate, onNotice }: { onboarding: Onboarding; settings: AccountingSettings; accounts: Account[]; onChanged: (value: Onboarding) => void; onNavigate: (page: PageKey) => void; onNotice: (value: string) => void }) {
  const [draft, setDraft] = useState(onboarding); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => setDraft(onboarding), [onboarding])
  const index = Math.max(0, Math.min(9, draft.current_step - 1)); const current = steps[index]; const progress = Math.round(((new Set([...draft.completed_steps, ...draft.skipped_steps])).size / steps.length) * 100)
  const catalogNeeded = draft.enabled_workflows.some((v) => ['SALES','PURCHASING','INVENTORY','MANUFACTURING'].includes(v))
  const openingEquity = accounts.find((a) => a.system_key === 'OPENING_BALANCE_EQUITY')
  const resolved = useMemo(() => new Set([...draft.completed_steps, ...draft.skipped_steps]), [draft])
  async function persist(next: Onboarding, message?: string) { setSaving(true); setError(null); try { const value = await saveOnboarding({ business_type: next.business_type, enabled_workflows: next.enabled_workflows, completed_steps: next.completed_steps, skipped_steps: next.skipped_steps, current_step: next.current_step, dismissed: Boolean(next.dismissed_at) }); setDraft(value); onChanged(value); if (message) onNotice(message); return value } catch (cause) { setError(apiError(cause)); throw cause } finally { setSaving(false) } }
  function nextState(kind: 'complete' | 'skip') { const key = current[0]; const completed = draft.completed_steps.filter((v) => v !== key); const skipped = draft.skipped_steps.filter((v) => v !== key); (kind === 'complete' ? completed : skipped).push(key); return { ...draft, completed_steps: completed, skipped_steps: skipped, current_step: Math.min(10, index + 2) } }
  async function complete(message?: string) { await persist(nextState('complete'), message) }
  async function skip() { await persist(nextState('skip'), `${current[1]} dilewati. Bisa dilengkapi nanti.`) }
  async function dismiss() { await persist({ ...draft, dismissed_at: new Date().toISOString() }, 'Checklist dipindahkan ke dashboard.'); onNavigate('company.dashboard') }
  async function company(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await run(async () => { await saveLocalization({ country_code: 'ID', legal_name: String(f.get('legal_name')), tax_identifier: String(f.get('tax_identifier')) || null, is_vat_registered: f.get('is_vat_registered') === 'on', vat_registration_number: String(f.get('vat_registration_number')) || null, statutory_timezone: settings.timezone }); await complete('Profil perusahaan disimpan.') }) }
  async function books(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await run(async () => { await updateSettings({ timezone: String(f.get('timezone')), fiscal_year_start_month: Number(f.get('fiscal_month')), enabled_modules: settings.enabled_modules }); await complete('Pengaturan buku diperbarui.') }) }
  async function business(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const workflows = workflowOptions.filter(([key]) => f.get(key) === 'on').map(([key]) => key); await run(() => persist({ ...nextState('complete'), business_type: String(f.get('business_type')) as Onboarding['business_type'], enabled_workflows: workflows }, 'Workflow bisnis diaktifkan.')) }
  async function opening(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const target = String(f.get('account_id')); const amount = String(f.get('amount')); const side = String(f.get('side')); if (!openingEquity) { setError('Akun ekuitas saldo awal tidak tersedia.'); return } const lines = side === 'DEBIT' ? [{ account_id: target, description: 'Saldo awal', debit: amount, credit: '0' }, { account_id: openingEquity.id, description: 'Ekuitas saldo awal', debit: '0', credit: amount }] : [{ account_id: target, description: 'Saldo awal', debit: '0', credit: amount }, { account_id: openingEquity.id, description: 'Ekuitas saldo awal', debit: amount, credit: '0' }]; await run(async () => { await postOpeningBalance({ transaction_date: String(f.get('date')), description: 'Saldo awal onboarding', lines }); await complete('Saldo awal diposting.') }) }
  async function contact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await run(async () => { await createContact({ type: String(f.get('type')), name: String(f.get('name')) }); await complete('Kontak pertama dibuat.') }) }
  async function invite(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await run(async () => { await createInvitation({ email: String(f.get('email')), role_code: String(f.get('role')) }); await complete('Undangan tim dibuat.') }) }
  async function finish() { const completed = Array.from(new Set([...draft.completed_steps, 'review'])); await run(async () => { const value = await persist({ ...draft, completed_steps: completed, current_step: 10 }, 'Setup selesai. Workspace siap digunakan.'); if (value.completed_at) onNavigate('company.dashboard') }) }
  async function run(action: () => Promise<unknown>) { setError(null); try { await action() } catch { /* rendered by persist or interceptor */ } }
  return <section><PageHeader eyebrow="GET STARTED" title="Siapkan Accounting dengan benar" description="Checklist adaptif membantu menyiapkan buku tanpa mewajibkan fitur kasir, outlet, atau inventory." action={<Button variant="ghost" onClick={() => void dismiss()}>Lanjut nanti</Button>} />
    <div className="onboarding-progress"><div><span>Progres setup</span><strong>{progress}%</strong></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><Badge tone={draft.completed_at ? 'success' : 'info'}>{draft.completed_at ? 'Selesai' : `Langkah ${index + 1} dari 10`}</Badge></div>
    <div className="onboarding-layout"><aside className="panel onboarding-steps">{steps.map(([key, title], i) => <button key={key} className={cx(i === index && 'active', resolved.has(key) && 'resolved')} onClick={() => setDraft((v) => ({ ...v, current_step: i + 1 }))}><span>{resolved.has(key) ? '✓' : i + 1}</span><div><strong>{title}</strong><small>{draft.skipped_steps.includes(key) ? 'Dilewati' : draft.completed_steps.includes(key) ? 'Selesai' : i === index ? 'Sedang dikerjakan' : 'Belum selesai'}</small></div></button>)}</aside>
      <Card className="onboarding-card"><div className="onboarding-card-head"><span>{String(index + 1).padStart(2, '0')}</span><div><p className="eyebrow">{current[1]}</p><h2>{current[2]}</h2></div></div>{error && <div className="auth-error">{error}</div>}
        {current[0] === 'company' && <form className="setup-form" onSubmit={(e) => void company(e)}><label>Nama legal perusahaan<input name="legal_name" placeholder="PT Contoh Indonesia" required /></label><label>NPWP<input name="tax_identifier" placeholder="Opsional" /></label><label className="check-row"><input name="is_vat_registered" type="checkbox" />Perusahaan terdaftar sebagai PKP</label><label>Nomor pengukuhan PKP<input name="vat_registration_number" /></label><WizardActions saving={saving} onSkip={skip} /></form>}
        {current[0] === 'books' && <form className="setup-form" onSubmit={(e) => void books(e)}><label>Zona waktu<input name="timezone" defaultValue={settings.timezone} required /></label><label>Awal tahun fiskal<select name="fiscal_month" defaultValue={settings.fiscal_year_start_month}>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>Bulan {i + 1}</option>)}</select></label><div className="setup-note">Mata uang fungsional saat ini <strong>{settings.currency_code}</strong>. Perubahan mata uang setelah transaksi harus melalui migrasi terkontrol.</div><WizardActions saving={saving} /></form>}
        {current[0] === 'business' && <form className="setup-form" onSubmit={(e) => void business(e)}><label>Jenis usaha<select name="business_type" defaultValue={draft.business_type}><option value="SERVICE">Jasa</option><option value="RETAIL">Retail</option><option value="DISTRIBUTION">Distribusi</option><option value="MANUFACTURING">Manufaktur</option><option value="OTHER">Lainnya</option></select></label><fieldset><legend>Workflow yang dibutuhkan</legend><div className="workflow-grid">{workflowOptions.map(([key, label]) => <label className="workflow-option" key={key}><input type="checkbox" name={key} defaultChecked={draft.enabled_workflows.includes(key)} /><span><strong>{label}</strong><small>Bisa diubah kemudian</small></span></label>)}</div></fieldset><WizardActions saving={saving} /></form>}
        {current[0] === 'coa' && <SetupChoice title={`${accounts.length} akun sudah tersedia`} text="Loka telah menyiapkan chart of accounts generik. Review atau impor akun tambahan sebelum transaksi dimulai." primary="Tandai sudah direview" onPrimary={() => void complete('Daftar akun sudah direview.')} secondary="Buka daftar akun" onSecondary={() => onNavigate('gl.account')} saving={saving} />}
        {current[0] === 'opening' && <form className="setup-form" onSubmit={(e) => void opening(e)}><div className="form-row"><label>Tanggal saldo<input type="date" name="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Akun<select name="account_id" required><option value="">Pilih akun</option>{accounts.filter((a) => a.id !== openingEquity?.id).map((a) => <option value={a.id} key={a.id}>{a.code} · {a.name}</option>)}</select></label></div><div className="form-row"><label>Posisi<select name="side"><option value="DEBIT">Debit</option><option value="CREDIT">Kredit</option></select></label><label>Nominal<input name="amount" inputMode="numeric" required /></label></div><div className="setup-note">Saldo akan diseimbangkan otomatis terhadap akun Ekuitas Saldo Awal.</div><WizardActions saving={saving} onSkip={skip} /></form>}
        {current[0] === 'contacts' && <form className="setup-form" onSubmit={(e) => void contact(e)}><label>Nama pelanggan atau supplier<input name="name" required /></label><label>Tipe<select name="type"><option>CUSTOMER</option><option>SUPPLIER</option><option>BOTH</option></select></label><WizardActions saving={saving} onSkip={skip} /></form>}
        {current[0] === 'catalog' && <SetupChoice title={catalogNeeded ? 'Siapkan master operasional' : 'Tidak wajib untuk jenis usaha ini'} text={catalogNeeded ? 'Tambahkan satuan, barang atau jasa, dan gudang dari halaman master data. Setelah itu kembali untuk melanjutkan.' : 'Workflow yang dipilih tidak memerlukan katalog atau gudang. Langkah ini aman dilewati.'} primary={catalogNeeded ? 'Tandai sudah disiapkan' : 'Lewati langkah'} onPrimary={() => void (catalogNeeded ? complete('Master produk ditandai siap.') : skip())} secondary={catalogNeeded ? 'Buka produk & gudang' : undefined} onSecondary={() => onNavigate('inventory.item')} saving={saving} />}
        {current[0] === 'controls' && <SetupChoice title="Atur nomor, bank, pajak, dan approval" text="Konfigurasi yang dibutuhkan berbeda untuk setiap perusahaan. Buka kontrol organisasi untuk detail atau lanjutkan dengan default aman." primary="Gunakan default" onPrimary={() => void complete('Kontrol dasar siap digunakan.')} secondary="Buka kontrol organisasi" onSecondary={() => onNavigate('company.info')} saving={saving} />}
        {current[0] === 'team' && <form className="setup-form" onSubmit={(e) => void invite(e)}><label>Email anggota<input type="email" name="email" required /></label><label>Peran<select name="role"><option>ACCOUNTANT</option><option>FINANCE</option><option>AUDITOR</option><option>READ_ONLY</option></select></label><WizardActions saving={saving} onSkip={skip} /></form>}
        {current[0] === 'review' && <div className="setup-review"><div className="readiness-grid"><div><span>Jenis usaha</span><strong>{draft.business_type}</strong></div><div><span>Workflow aktif</span><strong>{draft.enabled_workflows.length}</strong></div><div><span>Akun tersedia</span><strong>{accounts.length}</strong></div><div><span>Langkah teratasi</span><strong>{resolved.size}/10</strong></div></div><div className="setup-note">Konfigurasi dapat diubah kapan saja. Transaksi yang telah diposting tetap mengikuti audit dan period lock.</div><Button disabled={saving} onClick={() => void finish()}>{saving ? 'Menyelesaikan…' : 'Selesaikan setup'}</Button></div>}
      </Card></div>
  </section>
}

function WizardActions({ saving, onSkip }: { saving: boolean; onSkip?: () => Promise<void> }) { return <div className="setup-actions">{onSkip && <Button type="button" variant="ghost" onClick={() => void onSkip()}>Lewati</Button>}<Button disabled={saving}>{saving ? 'Menyimpan…' : 'Simpan & lanjutkan'}</Button></div> }
function SetupChoice({ title, text, primary, secondary, onPrimary, onSecondary, saving }: { title: string; text: string; primary: string; secondary?: string; onPrimary: () => void; onSecondary?: () => void; saving: boolean }) { return <div className="setup-choice"><div className="empty-icon">✓</div><h3>{title}</h3><p>{text}</p><div className="setup-actions">{secondary && <Button variant="secondary" onClick={onSecondary}>{secondary}</Button>}<Button disabled={saving} onClick={onPrimary}>{primary}</Button></div></div> }
function apiError(cause: unknown) { if (cause instanceof AxiosError) { const body = cause.response?.data as ApiEnvelope<unknown> | undefined; return body?.error?.details ?? body?.message ?? 'Setup belum berhasil disimpan.' } return 'Setup belum berhasil disimpan.' }
