import { type FormEvent, useEffect, useState } from 'react'
import { AxiosError } from 'axios'
import { completeManufacturing, createTaxPeriod, getLocalization, listFXRates, listManufacturingOrders, listPayrollRuns, listTaxPeriods, postPayroll, remeasureFX, saveForeignBalance, saveFXRate, saveLocalization } from '../api/accounting'
import type { Account, FXRate, LocalizationProfile, ManufacturingOrder, PayrollRun, StatutoryTaxPeriod } from '../types/accounting'
import { Badge, DataEntryGuide, EmptyState, PageHeader } from '../components/ui'

type Kind = 'compliance' | 'payroll' | 'manufacturing' | 'currency'
const today = new Date().toISOString().slice(0, 10)
const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const value = (form: FormData, key: string) => String(form.get(key) ?? '')

export function ModulePage({ kind, accounts, onNotice }: { kind: Kind; accounts: Account[]; onNotice: (value: string) => void }) {
  if (kind === 'compliance') return <Compliance onNotice={onNotice} />
  if (kind === 'payroll') return <Payroll accounts={accounts} onNotice={onNotice} />
  if (kind === 'manufacturing') return <Manufacturing accounts={accounts} onNotice={onNotice} />
  return <Currency accounts={accounts} onNotice={onNotice} />
}

const moduleGuides: Record<string, string[]> = {
  'INDONESIA LOCALIZATION': ['Lengkapi identitas wajib pajak dan status PKP, lalu simpan profil.', 'Pilih jenis serta rentang periode pajak.', 'Isi pajak keluaran, pajak masukan, dan jumlah yang dipotong, lalu buat workpaper.', 'Periksa hasilnya di daftar periode statutory sebelum review dan filing.'],
  'PAYROLL ACCOUNTING': ['Isi periode payroll dan tanggal pembayaran.', 'Masukkan identitas karyawan, gross, potongan, dan kontribusi perusahaan.', 'Pilih akun beban, utang payroll, dan akun pembayaran.', 'Periksa seluruh nilai lalu klik “Post payroll”.'],
  'MANUFACTURING ACCOUNTING': ['Isi nomor order, produk, tanggal selesai, dan jumlah produksi.', 'Masukkan biaya material, tenaga kerja langsung, dan overhead.', 'Pilih akun barang jadi, bahan baku, serta akun absorpsi.', 'Periksa total biaya lalu klik “Selesaikan & post”.'],
  'MULTI-CURRENCY': ['Simpan kurs penutupan beserta tanggal dan sumbernya.', 'Catat saldo valuta serta carrying amount dalam rupiah.', 'Pilih kurs dan akun gain/loss pada form Remeasure.', 'Post remeasurement untuk mencatat selisih kurs.'],
}
function PageHead({ eyebrow, title, description, badge }: { eyebrow: string; title: string; description: string; badge: string }) { return <><PageHeader eyebrow={eyebrow} title={title} description={description} action={<Badge tone="info">{badge}</Badge>} /><DataEntryGuide steps={moduleGuides[eyebrow]} /></> }
function AccountSelect({ name, accounts, types }: { name: string; accounts: Account[]; types?: string[] }) { const rows = types ? accounts.filter(a => types.includes(a.type)) : accounts; return <select name={name} required defaultValue=""><option value="" disabled>Pilih akun</option>{rows.map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select> }
function Empty({ text }: { text: string }) { return <EmptyState>{text}</EmptyState> }
function errorMessage(error: unknown) { return error instanceof AxiosError ? String(error.response?.data?.error?.details ?? error.message) : 'Permintaan gagal.' }

function Compliance({ onNotice }: { onNotice: (v: string) => void }) {
  const [profile, setProfile] = useState<LocalizationProfile | null>(null); const [periods, setPeriods] = useState<StatutoryTaxPeriod[]>([])
  async function refresh() { const [p, rows] = await Promise.all([getLocalization().catch(() => null), listTaxPeriods().catch(() => [])]); setProfile(p); setPeriods(rows) }
  useEffect(() => { void refresh() }, [])
  async function saveProfile(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { await saveLocalization({ country_code:'ID', legal_name:value(f,'legal_name'), tax_identifier:value(f,'tax_identifier')||null, is_vat_registered:f.get('is_vat_registered')==='on', vat_registration_number:value(f,'vat_registration_number')||null, statutory_timezone:'Asia/Jakarta' }); await refresh(); onNotice('Profil pajak Indonesia tersimpan.') } catch(err){onNotice(errorMessage(err))} }
  async function addPeriod(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f=new FormData(e.currentTarget); try { await createTaxPeriod({tax_type:value(f,'tax_type'),period_start:value(f,'start'),period_end:value(f,'end'),output_tax:value(f,'output'),input_tax:value(f,'input'),withheld:value(f,'withheld')}); e.currentTarget.reset(); await refresh(); onNotice('Kertas kerja pajak dibuat untuk direview.') } catch(err){onNotice(errorMessage(err))} }
  return <section><PageHead eyebrow="INDONESIA LOCALIZATION" title="Pajak yang siap direview, bukan ditebak" description="Profil legal dan kertas kerja periode PPN/PPh dengan status audit. Pelaporan final tetap melalui Coretax DJP." badge="Indonesia · Configurable" />
    <div className="callout"><strong>Compliance guardrail</strong><span>Tarif dan perlakuan pajak berubah menurut objek serta tanggal efektif. Loka menyimpan workpaper dan jejak review; konsultasikan filing final dengan konsultan pajak.</span></div>
    <div className="split-grid"><form className="panel form-panel" onSubmit={e=>void saveProfile(e)}><div className="section-title"><div><span className="section-icon">ID</span><h2>Identitas wajib pajak</h2></div><span className="status active">{profile?'Tersimpan':'Belum lengkap'}</span></div><label>Nama legal<input name="legal_name" required defaultValue={profile?.legal_name}/></label><label>NPWP / Tax ID<input name="tax_identifier" defaultValue={profile?.tax_identifier??''}/></label><label className="check-row"><input type="checkbox" name="is_vat_registered" defaultChecked={profile?.is_vat_registered}/><span>Terdaftar sebagai PKP</span></label><label>Nomor registrasi PKP<input name="vat_registration_number" defaultValue={profile?.vat_registration_number??''}/></label><button className="primary">Simpan profil</button></form>
    <form className="panel form-panel" onSubmit={e=>void addPeriod(e)}><div className="section-title"><div><span className="section-icon">%</span><h2>Workpaper periode</h2></div></div><div className="form-row"><label>Jenis<select name="tax_type"><option>PPN</option><option>PPH21</option><option>PPH23</option><option>PPH_FINAL</option></select></label><label>Mulai<input name="start" type="date" required/></label><label>Selesai<input name="end" type="date" required/></label></div><div className="form-row"><label>Pajak keluaran<input name="output" inputMode="numeric" defaultValue="0"/></label><label>Pajak masukan<input name="input" inputMode="numeric" defaultValue="0"/></label><label>Dipotong<input name="withheld" inputMode="numeric" defaultValue="0"/></label></div><button className="primary">Buat workpaper</button></form></div>
    <div className="panel data-panel"><div className="panel-heading"><div><h2>Periode statutory</h2><p>Draft, review, filing, dan pembayaran tetap dapat ditelusuri.</p></div></div>{periods.length===0?<Empty text="Belum ada periode pajak."/>:<div className="table-wrap"><table><thead><tr><th>Jenis</th><th>Periode</th><th>Status</th><th className="number">Terutang</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td><span className="type-tag">{p.tax_type}</span></td><td>{p.period_start.slice(0,10)} – {p.period_end.slice(0,10)}</td><td><span className="pill warning">{p.status}</span></td><td className="number">{money.format(p.payable_minor)}</td></tr>)}</tbody></table></div>}</div></section>
}

function Payroll({ accounts, onNotice }: { accounts: Account[]; onNotice:(v:string)=>void }) { const [rows,setRows]=useState<PayrollRun[]>([]);async function refresh(){setRows(await listPayrollRuns().catch(()=>[]))}useEffect(()=>{void refresh()},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await postPayroll({period_start:value(f,'start'),period_end:value(f,'end'),payment_date:value(f,'payment'),salary_expense_account_id:value(f,'salary'),contribution_expense_account_id:value(f,'contribution'),payroll_liability_account_id:value(f,'liability'),payment_account_id:value(f,'cash'),items:[{employee_reference:value(f,'employee_ref'),employee_name:value(f,'employee_name'),gross:value(f,'gross'),deductions:value(f,'deductions'),employer_contributions:value(f,'employer')}]});e.currentTarget.reset();await refresh();onNotice('Payroll diposting sebagai jurnal berimbang.')}catch(err){onNotice(errorMessage(err))}}
  return <section><PageHead eyebrow="PAYROLL ACCOUNTING" title="Posting payroll tanpa jurnal bayangan" description="Gross pay, potongan karyawan, kontribusi perusahaan, liability, dan pembayaran bersih tersimpan atomik." badge="Journal-backed"/><div className="stat-strip"><div><span>Total run</span><strong>{rows.length}</strong></div><div><span>Gross terakhir</span><strong>{money.format(rows[0]?.gross_minor??0)}</strong></div><div><span>Net terakhir</span><strong>{money.format(rows[0]?.net_minor??0)}</strong></div></div><form className="panel form-panel wide-form" onSubmit={e=>void submit(e)}><div className="section-title"><div><span className="section-icon">Rp</span><h2>Run payroll baru</h2></div></div><div className="form-row"><label>Awal periode<input name="start" type="date" required/></label><label>Akhir periode<input name="end" type="date" required/></label><label>Tanggal bayar<input name="payment" type="date" defaultValue={today} required/></label></div><div className="form-row"><label>ID karyawan<input name="employee_ref" required placeholder="EMP-001"/></label><label>Nama karyawan<input name="employee_name" required/></label><label>Gross<input name="gross" required inputMode="numeric"/></label><label>Potongan<input name="deductions" defaultValue="0" inputMode="numeric"/></label><label>Kontribusi perusahaan<input name="employer" defaultValue="0" inputMode="numeric"/></label></div><div className="form-row"><label>Beban gaji<AccountSelect name="salary" accounts={accounts} types={['EXPENSE']}/></label><label>Beban kontribusi<AccountSelect name="contribution" accounts={accounts} types={['EXPENSE']}/></label><label>Utang payroll<AccountSelect name="liability" accounts={accounts} types={['LIABILITY']}/></label><label>Akun pembayaran<AccountSelect name="cash" accounts={accounts} types={['ASSET']}/></label></div><button className="primary">Post payroll</button></form><History title="Riwayat payroll" empty="Belum ada payroll run." headers={['Periode','Tanggal bayar','Status','Net']} rows={rows.map(r=>[`${r.period_start.slice(0,10)} – ${r.period_end.slice(0,10)}`,r.payment_date.slice(0,10),r.status,money.format(r.net_minor)])}/></section> }

function Manufacturing({accounts,onNotice}:{accounts:Account[];onNotice:(v:string)=>void}){const[rows,setRows]=useState<ManufacturingOrder[]>([]);async function refresh(){setRows(await listManufacturingOrders().catch(()=>[]))}useEffect(()=>{void refresh()},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await completeManufacturing({order_number:value(f,'order'),product_reference:value(f,'product'),completion_date:value(f,'date'),quantity:Number(value(f,'qty')),raw_material:value(f,'raw'),direct_labor:value(f,'labor'),overhead:value(f,'overhead'),finished_goods_account_id:value(f,'fg_account'),raw_material_account_id:value(f,'raw_account'),labor_account_id:value(f,'labor_account'),overhead_account_id:value(f,'overhead_account')});e.currentTarget.reset();await refresh();onNotice('Order produksi selesai dan biaya dipindahkan ke barang jadi.')}catch(err){onNotice(errorMessage(err))}}
 return <section><PageHead eyebrow="MANUFACTURING ACCOUNTING" title="Biaya produksi yang bisa ditelusuri" description="Material, tenaga kerja langsung, dan overhead diserap ke persediaan barang jadi dalam satu transaksi." badge="Atomic costing"/><form className="panel form-panel wide-form" onSubmit={e=>void submit(e)}><div className="section-title"><div><span className="section-icon">MO</span><h2>Selesaikan production order</h2></div></div><div className="form-row"><label>Nomor order<input name="order" required placeholder="MO-2026-001"/></label><label>Produk<input name="product" required placeholder="SKU-FG-001"/></label><label>Tanggal selesai<input name="date" type="date" defaultValue={today} required/></label><label>Qty<input name="qty" type="number" min="1" required/></label></div><div className="form-row"><label>Material<input name="raw" defaultValue="0"/></label><label>Tenaga kerja<input name="labor" defaultValue="0"/></label><label>Overhead<input name="overhead" defaultValue="0"/></label></div><div className="form-row"><label>Barang jadi<AccountSelect name="fg_account" accounts={accounts} types={['ASSET']}/></label><label>Bahan baku<AccountSelect name="raw_account" accounts={accounts} types={['ASSET']}/></label><label>Absorpsi tenaga kerja<AccountSelect name="labor_account" accounts={accounts}/></label><label>Absorpsi overhead<AccountSelect name="overhead_account" accounts={accounts}/></label></div><button className="primary">Selesaikan & post</button></form><History title="Production orders" empty="Belum ada order produksi selesai." headers={['Order','Produk','Tanggal','Nilai barang jadi']} rows={rows.map(r=>[r.order_number,r.product_reference,r.completion_date.slice(0,10),money.format(r.finished_goods_minor)])}/></section>}

function Currency({accounts,onNotice}:{accounts:Account[];onNotice:(v:string)=>void}){const[rates,setRates]=useState<FXRate[]>([]);async function refresh(){setRates(await listFXRates().catch(()=>[]))}useEffect(()=>{void refresh()},[]);async function rate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await saveFXRate({currency_code:value(f,'currency'),rate_date:value(f,'date'),rate_numerator:Number(value(f,'numerator')),rate_denominator:Number(value(f,'denominator')),source:value(f,'source')});await refresh();onNotice('Kurs exact tersimpan.')}catch(err){onNotice(errorMessage(err))}}async function balance(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await saveForeignBalance({account_id:value(f,'account'),currency_code:value(f,'currency'),foreign_amount:value(f,'foreign'),carrying_base_amount:value(f,'base')});onNotice('Saldo valuta tersimpan.')}catch(err){onNotice(errorMessage(err))}}async function remeasure(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await remeasureFX({rate_id:value(f,'rate'),remeasurement_date:value(f,'date'),gain_loss_account_id:value(f,'gain_loss')});onNotice('Remeasurement diposting.')}catch(err){onNotice(errorMessage(err))}}
 return <section><PageHead eyebrow="MULTI-CURRENCY" title="Kurs presisi, selisih transparan" description="Simpan kurs sebagai pecahan exact, catat carrying amount, lalu post unrealized gain/loss pada penutupan periode." badge="Functional currency · IDR"/><div className="three-grid"><form className="panel form-panel" onSubmit={e=>void rate(e)}><h2>1 · Kurs penutupan</h2><label>Mata uang<input name="currency" maxLength={3} placeholder="USD" required/></label><div className="form-row"><label>Numerator<input name="numerator" type="number" min="1" required placeholder="1650000"/></label><label>Denominator<input name="denominator" type="number" min="1" required placeholder="100"/></label></div><label>Tanggal<input name="date" type="date" defaultValue={today} required/></label><label>Sumber<input name="source" required placeholder="Bank Indonesia / contract rate"/></label><button className="primary">Simpan kurs</button></form><form className="panel form-panel" onSubmit={e=>void balance(e)}><h2>2 · Saldo valuta</h2><label>Akun<AccountSelect name="account" accounts={accounts} types={['ASSET','LIABILITY']}/></label><label>Mata uang<input name="currency" maxLength={3} placeholder="USD" required/></label><label>Saldo valuta<input name="foreign" required/></label><label>Carrying amount IDR<input name="base" required/></label><button className="primary">Simpan saldo</button></form><form className="panel form-panel" onSubmit={e=>void remeasure(e)}><h2>3 · Remeasure</h2><label>Kurs<select name="rate" required><option value="">Pilih kurs</option>{rates.map(r=><option value={r.id} key={r.id}>{r.currency_code} · {r.rate_date.slice(0,10)} · {r.rate_numerator}/{r.rate_denominator}</option>)}</select></label><label>Tanggal<input name="date" type="date" defaultValue={today} required/></label><label>Akun gain/loss<AccountSelect name="gain_loss" accounts={accounts} types={['OTHER_INCOME','OTHER_EXPENSE']}/></label><button className="primary">Post remeasurement</button></form></div><History title="Kurs tersimpan" empty="Belum ada kurs valuta." headers={['Mata uang','Tanggal','Exact rate','Sumber']} rows={rates.map(r=>[r.currency_code,r.rate_date.slice(0,10),`${r.rate_numerator} / ${r.rate_denominator}`,r.source])}/></section>}

function History({title,empty,headers,rows}:{title:string;empty:string;headers:string[];rows:string[][]}){return <div className="panel data-panel"><div className="panel-heading"><h2>{title}</h2></div>{rows.length===0?<Empty text={empty}/>:<div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}</div>}
